from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1013, 835)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 100, 891, 481))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        self.tableWidget.setMaximumSize(QtCore.QSize(861, 428))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(210)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(730, 590, 191, 121))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.metacriterionLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.metacriterionLineEdit.setEnabled(True)
        self.metacriterionLineEdit.setReadOnly(True)
        self.metacriterionLineEdit.setObjectName("metacriterionLineEdit")
        self.verticalLayout_8.addWidget(self.metacriterionLineEdit)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(30, 590, 391, 194))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.shareholdingTable = QtWidgets.QTableWidget(self.verticalLayoutWidget_4)
        self.shareholdingTable.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shareholdingTable.sizePolicy().hasHeightForWidth())
        self.shareholdingTable.setSizePolicy(sizePolicy)
        self.shareholdingTable.setObjectName("shareholdingTable")
        self.shareholdingTable.setColumnCount(2)
        self.shareholdingTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.shareholdingTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.shareholdingTable.setHorizontalHeaderItem(1, item)
        self.shareholdingTable.horizontalHeader().setSortIndicatorShown(False)
        self.shareholdingTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.shareholdingTable, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(550, 10, 331, 60))
        self.label_6.setAcceptDrops(False)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.ratioLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.ratioLineEdit.setGeometry(QtCore.QRect(650, 60, 137, 22))
        self.ratioLineEdit.setDragEnabled(False)
        self.ratioLineEdit.setReadOnly(False)
        self.ratioLineEdit.setObjectName("ratioLineEdit")
        self.evaluateButton = QtWidgets.QPushButton(self.centralwidget)
        self.evaluateButton.setGeometry(QtCore.QRect(900, 40, 93, 28))
        self.evaluateButton.setObjectName("evaluateButton")
        self.chooseFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.chooseFileButton.setGeometry(QtCore.QRect(40, 20, 469, 28))
        self.chooseFileButton.setObjectName("chooseFileButton")
        self.filePathLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.filePathLineEdit.setEnabled(True)
        self.filePathLineEdit.setGeometry(QtCore.QRect(40, 60, 469, 22))
        self.filePathLineEdit.setReadOnly(True)
        self.filePathLineEdit.setObjectName("filePathLineEdit")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(550, 590, 181, 121))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1013, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setAccessibleName("")
        self.statusbar.setAccessibleDescription("")
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Portfel inwestycyjny"))
        item = self.shareholdingTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Spółka"))
        item = self.shareholdingTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Udziały spółki"))
        self.label_6.setText(_translate("MainWindow", "Wprowadź stosunek kryterium ryzyka do kryterium zysku"))
        self.evaluateButton.setText(_translate("MainWindow", "Oblicz"))
        self.chooseFileButton.setText(_translate("MainWindow", "Wybierz plik CSV"))
        self.filePathLineEdit.setText(_translate("MainWindow", "ścieżka do pliku"))
        self.label_5.setText(_translate("MainWindow", "Wartość funkcji metakryterium"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

